from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "zh" / "index.html"

REPLACEMENTS = [
    ("Audit → Diagnosis → Blueprint", "审计 → 诊断 → 优化蓝图"),
    ("Evidence · Entity · Citation", "证据 · 实体 · 引用"),
    ("Health ≠ Growth", "健康 ≠ 增长"),
    ("Health vs Growth", "健康与增长"),
    ("看 Health 与 Growth", "看健康度与增长"),
    ("对比 Health 与 Growth", "对比健康度与增长"),
    ("SEO Health", "SEO 健康度"),
    ("SEO Growth", "SEO 增长"),
    ("GEO Health", "GEO 健康度"),
    ("GEO Growth", "GEO 增长"),
    ("Deep Audit", "深度审计"),
    ("Question Coverage", "问题覆盖度"),
    ("Entity clarity", "实体清晰度"),
    ("Answerability", "可回答性"),
    ("Evidence coverage", "证据覆盖度"),
    ("Citation readiness", "引用准备度"),
    ("Overall Score", "总分"),
    ("Evidence（证据）", "证据"),
    ("Coverage（覆盖）", "覆盖"),
    ("Query gaps（查询缺口）", "查询缺口"),
    ("Citation（引用）", "引用"),
    ("Audit（审计）", "审计"),
    ("Diagnosis（诊断）", "诊断"),
    ("Blueprint（蓝图）", "优化蓝图"),
    ("健康（Healthy）", "健康"),
    ("增长（Growing）", "增长"),
    ("Health 告诉你哪些在正常工作。Growth 指出还缺什么。", "健康度告诉你哪些在正常工作。增长指出还缺什么。"),
    ("用 Health 稳住基础；用 Growth 看清还有哪些需求未被回答。", "用健康度稳住基础；用增长看清还有哪些需求未被回答。"),
    ("然后才写 Blueprint。", "然后才写优化蓝图。"),
    ("Blueprint 把归组变成带优先级与验收的工作。", "优化蓝图把归组变成带优先级与验收的工作。"),
    ("示例 Blueprint 动作", "示例优化蓝图动作"),
    ("Blueprint 是指导", "优化蓝图是指导"),
    ("含 Blueprint 动作", "含优化蓝图动作"),
    ("写成带目标页面的 Blueprint 动作", "写成带目标页面的优化蓝图动作"),
    ("写进 Blueprint。", "写进优化蓝图。"),
    ("可执行的 Blueprint", "可执行的优化蓝图"),
    ("生成可引用的 Blueprint", "生成可引用的优化蓝图"),
    (">SCAN<", ">扫描<"),
    (">DIAGNOSE<", ">诊断<"),
    (">BLUEPRINT<", ">优化蓝图<"),
    (">OPTIMIZE<", ">优化<"),
    (">RE-AUDIT<", ">复审<"),
    (">Evidence<", ">证据<"),
    (">Blueprint<", ">优化蓝图<"),
    (">Website<", ">网站<"),
    (">Page<", ">页面<"),
    ('data-tag="page">Page<', 'data-tag="page">页面<'),
    ("SEO 与 GEO 分轨；Health 与 Growth 分尺。没有把它们揉成一个 总分。", "SEO 与 GEO 分轨；健康度与增长分尺。没有把它们揉成一个总分。"),
    ("Technical（技术）", "技术"),
    ("Structure（结构）", "结构"),
    ("Content（内容）", "内容"),
    ("Understanding（理解）", "理解"),
    ("Answers（答案）", "答案"),
    ("Intent（意图）", "意图"),
    ("Depth（深度）", "深度"),
    ("Markets（市场）", "市场"),
    ("Answer gaps（答案缺口）", "答案缺口"),
    ("Expansion（扩展）", "扩展"),
    (">Crawling<", ">抓取<"),
    (">pages<", ">页面<"),
    (">Architecture<", ">架构<"),
    (">internal links<", ">内链<"),
    (">Content<", ">内容<"),
    (">topics<", ">主题<"),
    (">Search intent<", ">搜索意图<"),
    (">commercial intents<", ">商业意图<"),
    (">Entities<", ">实体<"),
    (">entities<", ">实体<"),
    (">Questions<", ">问题<"),
    (">buyer questions<", ">买家问题<"),
    (">evidence items<", ">条证据<"),
    (">Languages<", ">语言<"),
    (">languages<", ">种语言<"),
    (">Images<", ">图片<"),
    (">images<", ">张图片<"),
    (">Links<", ">链接<"),
    (">Topics<", ">主题<"),
    (">Gaps<", ">缺口<"),
    (">SEO HEALTH<", ">SEO 健康度<"),
    (">SEO GROWTH<", ">SEO 增长<"),
    (">Crawlability<", ">可抓取性<"),
    (">On-page<", ">页面基础<"),
    (">Internal links<", ">内链<"),
    (">Topic<", ">主题<"),
    (">Intent<", ">意图<"),
    (">Commercial<", ">商业意图<"),
    (">Market<", ">市场<"),
    (">Topical depth<", ">主题深度<"),
    (">Content depth<", ">内容深度<"),
    (">Expand product page<", ">扩展产品页<"),
    (">Add product definition<", ">补充产品定义<"),
    (">Add use case<", ">补充使用场景<"),
    (">Add specifications<", ">补充规格<"),
    (">Add evidence<", ">补充证据<"),
    (">Add FAQ<", ">补充常见问题<"),
    ("Priority <strong>P1</strong>", "优先级 <strong>P1</strong>"),
    ("Validation <strong>re-audit</strong>", "验收 <strong>复审</strong>"),
    (">Topic gap<", ">主题缺口<"),
    (">Commercial gap<", ">商业缺口<"),
    (">Market gap<", ">市场缺口<"),
    (">Depth gap<", ">深度缺口<"),
    (">topic opportunities<", ">个主题机会<"),
    (">commercial intents<", ">个商业意图<"),
    (">market expansions<", ">个市场扩展<"),
    (">pages worth expanding<", ">个值得扩展的页面<"),
    (">Question<", ">问题<"),
    (">Topic<", ">主题<"),
    (">Intent<", ">意图<"),
    (">Entity<", ">实体<"),
    (">Direct Answer<", ">直接答案<"),
    (">questions analyzed<", ">个问题已分析<"),
    (">Answered<", ">已回答<"),
    (">Partial<", ">部分回答<"),
    (">Uncovered<", ">未覆盖<"),
    (">total<", ">总计<"),
    (">covered<", ">已覆盖<"),
    (">partial<", ">部分<"),
    (">missing<", ">缺失<"),
    ('data-tag="intent">Intent<', 'data-tag="intent">意图<'),
    ('data-tag="answer">Answer<', 'data-tag="answer">答案<'),
    ('data-tag="commercial">commercial<', 'data-tag="commercial">商业<'),
    ('data-tag="topic">topic<', 'data-tag="topic">主题<'),
    ('data-tag="product">product<', 'data-tag="product">产品<'),
    ('data-tag="evidence">evidence<', 'data-tag="evidence">证据<'),
    (">Company<", ">公司<"),
    (">Products<", ">产品<"),
    (">Applications<", ">应用<"),
    (">Technical Information<", ">技术信息<"),
    (">Documentation<", ">文档<"),
    (">Consistency<", ">一致性<"),
    (">Company name<", ">公司名称<"),
    (">Product name<", ">产品名称<"),
    (">Specifications<", ">规格<"),
    (">Applications<", ">应用<"),
    (">Claims<", ">主张<"),
    (">Question coverage<", ">问题覆盖<"),
    (">pass<", ">通过<"),
    (">watch<", ">待补<"),
    ("保持 Health 与 Growth 分轨计分。", "保持健康度与增长分轨计分。"),
    (">Your website<", ">你的网站<"),
    (">Search<", ">搜索<"),
    (">Questions<", ">问题<"),
    (">Gaps<", ">缺口<"),
]


def main() -> None:
    text = TARGET.read_text(encoding="utf-8")
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    TARGET.write_text(text, encoding="utf-8")
    print("localized", TARGET)


if __name__ == "__main__":
    main()
