/**
 * Knowledge Center article registry (SSOT for index cards & docs).
 * Article bodies live at /knowledge/{slug}/ and /zh/knowledge/{slug}/ (other lane).
 * Categories: seo | geo | search-visibility | content | technical | research | open-source | updates
 */
window.KC_ARTICLES = [
  /* —— SEO —— */
  { slug: "what-is-a-website-seo-audit", category: "seo", featured: true, date: "2026-09-22",
    en: { title: "What Is a Website SEO Audit", blurb: "What a structured SEO audit covers—and what it does not claim to predict." },
    zh: { title: "什么是网站 SEO 审计", blurb: "结构化 SEO 审计覆盖哪些层面，以及它不会承诺什么。" } },
  { slug: "how-to-check-website-crawlability", category: "seo", featured: true, date: "2026-09-23",
    en: { title: "How to Check Website Crawlability", blurb: "Practical checks for robots rules, status codes, and crawl paths." },
    zh: { title: "如何检查网站可抓取性", blurb: "针对 robots、状态码与抓取路径的实用检查。" } },
  { slug: "how-to-find-broken-internal-links", category: "seo", featured: false, date: "2026-09-23",
    en: { title: "How to Find Broken Internal Links", blurb: "Find dead internal links that waste crawl budget and user trust." },
    zh: { title: "如何查找失效内链", blurb: "找出浪费抓取预算并损害信任的失效内链。" } },
  { slug: "how-to-audit-canonical-urls", category: "seo", featured: false, date: "2026-09-23",
    en: { title: "How to Audit Canonical URLs", blurb: "Verify canonical tags point to the intended indexable URL." },
    zh: { title: "如何审计规范 URL（Canonical）", blurb: "核对 canonical 是否指向预期的可索引地址。" } },
  { slug: "how-to-check-hreflang", category: "seo", featured: false, date: "2026-09-23",
    en: { title: "How to Check Hreflang", blurb: "Validate language/region alternates without guessing rankings." },
    zh: { title: "如何检查 Hreflang", blurb: "校验语言与地区备用链接，而不猜测排名。" } },
  { slug: "how-to-analyze-xml-sitemaps", category: "seo", featured: false, date: "2026-09-22",
    en: { title: "How to Analyze XML Sitemaps", blurb: "Read sitemap coverage, freshness, and indexation mismatches." },
    zh: { title: "如何分析 XML Sitemap", blurb: "解读覆盖范围、更新频率与索引不一致。" } },
  { slug: "how-to-find-orphan-pages", category: "seo", featured: false, date: "2026-09-22",
    en: { title: "How to Find Orphan Pages", blurb: "Locate pages with no internal links and weak discovery paths." },
    zh: { title: "如何发现孤立页面", blurb: "找出缺少内链、发现路径薄弱的页面。" } },
  { slug: "how-to-detect-duplicate-content", category: "seo", featured: false, date: "2026-09-22",
    en: { title: "How to Detect Duplicate Content", blurb: "Spot near-duplicates and thin template collisions." },
    zh: { title: "如何检测重复内容", blurb: "识别近重复页面与薄弱模板冲突。" } },
  { slug: "how-to-find-content-gaps", category: "seo", featured: true, date: "2026-09-22",
    en: { title: "How to Find Content Gaps", blurb: "Compare buyer questions with what your site actually answers." },
    zh: { title: "如何发现内容缺口", blurb: "对照买家问题与站点实际回答的差距。" } },
  { slug: "how-to-map-search-intent", category: "seo", featured: false, date: "2026-09-22",
    en: { title: "How to Map Search Intent", blurb: "Align pages to informational, commercial, and transactional intent." },
    zh: { title: "如何映射搜索意图", blurb: "让页面匹配信息、商业与交易类意图。" } },
  { slug: "how-to-build-topic-coverage", category: "seo", featured: false, date: "2026-09-22",
    en: { title: "How to Build Topic Coverage", blurb: "Grow topical depth without manufacturing near-duplicate pages." },
    zh: { title: "如何建设主题覆盖", blurb: "加深主题覆盖，而不是批量制造近重复页。" } },
  { slug: "how-to-identify-commercial-search-opportunities", category: "seo", featured: false, date: "2026-09-22",
    en: { title: "How to Identify Commercial Search Opportunities", blurb: "Find commercial queries your product pages can honestly support." },
    zh: { title: "如何识别商业搜索机会", blurb: "找到产品页能诚实支撑的商业查询。" } },
  { slug: "how-to-build-product-page-content", category: "seo", featured: false, date: "2026-09-22",
    en: { title: "How to Build Product Page Content", blurb: "Structure specs, use cases, and proof buyers need before contact." },
    zh: { title: "如何撰写产品页内容", blurb: "组织规格、场景与联系前所需的证据。" } },
  { slug: "how-to-expand-seo-into-new-markets", category: "seo", featured: false, date: "2026-09-22",
    en: { title: "How to Expand SEO into New Markets", blurb: "Enter new languages or regions with real coverage—not copy spam." },
    zh: { title: "如何把 SEO 扩展到新市场", blurb: "用真实覆盖进入新语言或地区，而非复制垃圾页。" } },
  { slug: "why-page-count-does-not-equal-seo-growth", category: "seo", featured: true, date: "2026-09-22",
    en: { title: "Why Page Count Does Not Equal SEO Growth", blurb: "More URLs are not the same as more findable, useful coverage." },
    zh: { title: "为什么页面数量不等于 SEO 增长", blurb: "更多 URL 并不等于更多可发现、有用的覆盖。" } },

  /* —— GEO —— */
  { slug: "what-is-geo", category: "geo", featured: true, date: "2026-09-22",
    en: { title: "What Is GEO", blurb: "A clear definition of Generative Engine Optimization for B2B sites." },
    zh: { title: "什么是 GEO", blurb: "面向 B2B 站点的生成式引擎优化清晰定义。" } },
  { slug: "how-to-make-company-information-clearer", category: "geo", featured: false, date: "2026-09-22",
    en: { title: "How to Make Company Information Clearer", blurb: "State who you are, what you sell, and where you operate—without hype." },
    zh: { title: "如何让公司信息更清晰", blurb: "清楚说明你是谁、卖什么、在哪里运营。" } },
  { slug: "how-to-structure-product-information", category: "geo", featured: false, date: "2026-09-22",
    en: { title: "How to Structure Product Information", blurb: "Make product facts extractable for people and answer systems." },
    zh: { title: "如何结构化产品信息", blurb: "让产品事实便于人与回答系统提取。" } },
  { slug: "how-to-answer-buyer-questions-directly", category: "geo", featured: true, date: "2026-09-22",
    en: { title: "How to Answer Buyer Questions Directly", blurb: "Put short, sourceable answers on real pages—not only marketing copy." },
    zh: { title: "如何直接回答买家问题", blurb: "在真实页面给出可溯源短答，而不只是营销文案。" } },
  { slug: "how-to-build-evidence-around-product-claims", category: "geo", featured: false, date: "2026-09-22",
    en: { title: "How to Build Evidence Around Product Claims", blurb: "Support claims with specs, process, and verifiable context." },
    zh: { title: "如何为产品主张建立证据", blurb: "用规格、流程与可核验上下文支撑主张。" } },
  { slug: "how-to-improve-citation-readiness", category: "geo", featured: false, date: "2026-09-22",
    en: { title: "How to Improve Citation Readiness", blurb: "Make pages easier to quote—without promising guaranteed citations." },
    zh: { title: "如何提升被引用就绪度", blurb: "让页面更易被引用——但不承诺保证引用。" } },
  { slug: "how-to-build-consistent-entity-information", category: "geo", featured: false, date: "2026-09-22",
    en: { title: "How to Build Consistent Entity Information", blurb: "Keep names, products, and facts consistent across languages." },
    zh: { title: "如何建设一致的实体信息", blurb: "在多语言间保持名称、产品与事实一致。" } },
  { slug: "how-to-audit-ai-search-visibility", category: "geo", featured: true, date: "2026-09-22",
    en: { title: "How to Audit AI Search Visibility", blurb: "A checklist for answerability, entities, and evidence—not ranking guarantees." },
    zh: { title: "如何审计 AI 搜索可见度", blurb: "可答性、实体与证据清单——不是排名保证。" } },
  { slug: "what-makes-a-page-easier-to-reference", category: "geo", featured: false, date: "2026-09-22",
    en: { title: "What Makes a Page Easier to Reference", blurb: "Structure, definitions, and evidence that help other systems cite you." },
    zh: { title: "什么让页面更容易被引用", blurb: "有助于其他系统引用你的结构、定义与证据。" } },

  /* —— Search Visibility / Content / Technical —— */
  { slug: "seo-health-vs-seo-growth", category: "search-visibility", featured: true, date: "2026-09-23",
    en: { title: "SEO Health vs SEO Growth", blurb: "Separate crawl/index health from topic and market expansion." },
    zh: { title: "SEO 健康 vs SEO 增长", blurb: "把抓取/索引健康与主题、市场扩展分开看。" } },
  { slug: "geo-health-vs-geo-growth", category: "search-visibility", featured: true, date: "2026-09-23",
    en: { title: "GEO Health vs GEO Growth", blurb: "Clarity and evidence today versus uncovered questions tomorrow." },
    zh: { title: "GEO 健康 vs GEO 增长", blurb: "今天的清晰与证据，对比明天尚未覆盖的问题。" } },
  { slug: "audit-diagnosis-blueprint", category: "technical", featured: true, date: "2026-09-23",
    en: { title: "Audit Diagnosis Blueprint", blurb: "A repeatable path from findings to prioritized next actions." },
    zh: { title: "审计诊断蓝图", blurb: "从发现到优先级行动的可重复路径。" } },
  { slug: "question-coverage-for-websites", category: "content", featured: false, date: "2026-09-23",
    en: { title: "Question Coverage for Websites", blurb: "Map buyer questions to pages that answer them directly." },
    zh: { title: "网站的问题覆盖", blurb: "把买家问题映射到能直接回答的页面。" } },
  { slug: "entity-evidence-answerability", category: "content", featured: false, date: "2026-09-23",
    en: { title: "Entity, Evidence & Answerability", blurb: "Three building blocks of trustworthy website answers." },
    zh: { title: "实体、证据与可答性", blurb: "可信网站回答的三个基础构件。" } },
  { slug: "multilingual-search-visibility", category: "search-visibility", featured: false, date: "2026-09-23",
    en: { title: "Multilingual Search Visibility", blurb: "Keep EN/ZH coverage aligned without /en/ prefixes or thin mirrors." },
    zh: { title: "多语言搜索可见度", blurb: "对齐中英文覆盖，避免 /en/ 前缀与薄弱镜像页。" } },

  /* —— Research / Open Source —— */
  { slug: "what-open-source-seo-crawlers-check", category: "open-source", featured: false, research: true, date: "2026-09-22",
    en: { title: "What Open-Source SEO Crawlers Check", blurb: "A field map of signals common open-source crawlers inspect." },
    zh: { title: "开源 SEO 爬虫检查什么", blurb: "常见开源爬虫会检查的信号图谱。" } },
  { slug: "how-geo-handbooks-structure-source-backed-pages", category: "research", featured: false, research: true, date: "2026-09-22",
    en: { title: "How GEO Handbooks Structure Source-Backed Pages", blurb: "Patterns for definitions, short answers, examples, and sources." },
    zh: { title: "GEO 手册如何组织有来源的页面", blurb: "定义、短答、例子与来源的页面组织方式。" } },
  { slug: "what-a-technical-seo-geo-crawler-inspects", category: "technical", featured: false, research: true, date: "2026-09-22",
    en: { title: "What a Technical SEO/GEO Crawler Inspects", blurb: "Technical and answerability signals a combined crawler can surface." },
    zh: { title: "技术 SEO/GEO 爬虫会检查什么", blurb: "组合爬虫可暴露的技术与可答性信号。" } },
  { slug: "how-source-backed-bilingual-sites-are-structured", category: "research", featured: false, research: true, date: "2026-09-22",
    en: { title: "How Source-Backed Bilingual Sites Are Structured", blurb: "Architecture notes for parallel EN/ZH sites with shared facts." },
    zh: { title: "有来源的双语站点如何组织", blurb: "共享事实的中英文并行站点架构要点。" } }
];

window.KC_CATEGORIES = [
  { id: "seo", en: "SEO", zh: "SEO" },
  { id: "geo", en: "GEO", zh: "GEO" },
  { id: "search-visibility", en: "Search Visibility", zh: "搜索可见度" },
  { id: "content", en: "Content", zh: "内容" },
  { id: "technical", en: "Technical", zh: "技术" },
  { id: "research", en: "Research", zh: "研究" },
  { id: "open-source", en: "Open Source", zh: "开源" },
  { id: "updates", en: "Updates", zh: "更新" }
];
